name = "workbin"
account_id = "c8526a45c47706d6c69f8d997004bd7a"
routes = [
    "workbin.dev/*",
    "paste.disnake.dev/*",
    "paste.nextcord.dev/*",
    "p.vco.sh/*",
]
compatibility_date = "2021-12-19"
kv_namespaces = [
    { binding = "WORKBIN", id = "a20fc5453a25469282397e99003e2f9b", preview_id = "a20fc5453a25469282397e99003e2f9b" },
]

[build]
command = "npm install && npm run build"
